@startuml usecase-pos

actor Gestionnaire as "Gestionnaire de maison mère"
actor Employe as "Employé de magasin"
actor Responsable as "Responsable logistique"
actor App as "Application" 

usecase "Générer un rapport consolidé des ventes" as UC1
usecase "Consulter le stock central et déclencher un réapprovisionnement" as UC2
usecase "Visualiser les performances des magasins dans un tableau de bord" as UC3
usecase "Mettre à jour les produits depuis la maison mère" as UC4
usecase "Approvisionner un magasin depuis le centre logistique" as UC6
usecase "Alerter automatiquement la maison mère en cas de rupture critique" as UC7
usecase "Offrir une interface web minimale pour les gestionnaires" as UC8

Gestionnaire --> UC1
Employe --> UC2
Gestionnaire --> UC3
Responsable --> UC4
Responsable --> UC6
App --> UC7
App --> UC8

@enduml
