@startuml usecase-pos

actor Employe

usecase "Rechercher un produit" as UC1
usecase "Enregistrer une vente" as UC2
usecase "Gérer un retour" as UC3
usecase "Consulter l'état du stock" as UC4

Employe --> UC1
Employe --> UC2
Employe --> UC3
Employe --> UC4

@enduml
